seed_everything: 42
model:  
  class_path: models.BasicMLP.BasicMLP # CHOOSE MODEL
  init_args:
    lr: 1e-3 
    d_input: 2
    n_features: 256
    n_layers: 8
    n_output: 1  
    linear_fn: layers.layers.ComplexLinear
    loss_fn: losses.MSE.MSELoss
    act_fn: layers.activations.Cardioid
    norm_fn: torch.nn.Identity
    metrics: 
      - class_path:  losses.MSE.NRMSELoss
data:
  class_path:  data.DataModules.GenericDataModule
  init_args:
    batch_size: null # set to None (null) to use full image
    num_workers: 8
    use_worker_init_fn: True
    train: data.Datasets.WrapedDataset # CHOOSE DATASET
trainer:
  max_epochs: 100
  log_every_n_steps: 1  # set to 1 if batch size is None
  benchmark: True
  accumulate_grad_batches: 2
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: 'logs/basic'  # CHANGE THIS
      name: 'basic' # CHANGE THIS
      version: 1 # CHANGE THIS
  callbacks:
    class_path: callbacks.BasicImageLogger.BasicImageLogger
    init_args:
      save_freq: 10
      best_only: false
      view_transforms: 
        - class_path:  transforms.Transforms.PhaseTransform
          dict_kwargs:
            cmap: "gray"
            vmin: -3.14
            vmax: 3.14
        - class_path:  transforms.Transforms.MagnitudeTransform
          dict_kwargs:
            cmap: "gray"

